//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "id": "6419c4029773748f3e22062c"
}

###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Test321",
  "email": "test321@mail.com",
  "password": "test"
}

###

// LOGGA IN USER // VID FEL LÖSENORD SÅ SKALL SVARA MED 401
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "testok@mail.co",
  "password": "test"
}

###

//
// API ENDPOINTS PRODUCTS
//

# @name getProducts
GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/64198321f3ab325509c57a6f

###

// SKAPA PRODUKT // UTAN TOKEN SÅ SKALL ANROPET MISSLYCKAS = 401
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Tiny sunglasses",
  "description": "Whos there?!",
  "price": 499,
  "lager": 20,
  "category": "sunglasses",
  "token": "1234key1234"
}

###

// HÄMTA ALLA PRODUKTER FÖR EN SPECIFIK KATEGORI
GET http://localhost:3000/api/products/category/shoes
###

//
// API ENDPOINTS KATEGORI
// 

// SKAPA KATEGORI, KEY MÅSTE ANGES // UTAN KEY SVARA 401
# @name createCategory
POST http://localhost:3000/api/categories/add
Content-Type: application/json

{
  "name": "gloves",
  "token": "1234key1234"
}

###

# @name getCategories
GET http://localhost:3000/api/categories

###

//
// API ENDPOINTS ORDERS
//

// HÄMTA ALLA ORDERS, KEY MÅSTE ANGES FÖR ATT FÅ TILLGÅNG TILL ORDERS
GET http://localhost:3000/api/orders/all/1234key1234

###

// HÄMTA ALLA ORDER, FEL KEY // SKALL MISSLYCKAS
GET http://localhost:3000/api/orders/all/felkey

###

// SKAPA ORDER FÖR EN SPECIFIK USER
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  "user": "641ae2f075caba1527efe90a",
  "products": [
    {
      "productId": "6419835cf3ab325509c57a72",
      "quantity": 1
    }
  ]
}

###

// HÄMTA ORDERS FÖR EN USER // SKALL MISSLYCKAS = INGEN KEY  // SVARA MED 401
POST http://localhost:3000/api/orders/user
Content-Type: application/json

{
    "user": "6419bd0c5ebfb0bacfdae5ce"
}
###

// HÄMTA ORDERS FÖR EN USER // SKALL LYCKAS = KEY
POST http://localhost:3000/api/orders/user
Content-Type: application/json

{
    "user": "6419c4029773748f3e22062c",
    "token": "1234key1234"
}
###